### ISSUE TITLE
Static version of FlyingThings3D

### ISSUE THREAD

**Issue by IgorVasiljevic-TRI** [lmb-freiburg/robustmvd#3]
A quick question to properly replicate the train setup -- could you share the static split for FlyingThings3D?  Thank you!

**Comment by pschroeppel** [comment]
Hi,
I think we already resolved this issue via mail. By now, the StaticThings3D data is available, see [the data README file](https://github.com/lmb-freiburg/robustmvd/blob/master/rmvd/data/README.md).
best,
Philipp
