### ISSUE TITLE
About key frames selection of ETH3D

### ISSUE THREAD

**Issue by yuqunw** [lmb-freiburg/robustmvd#4]
Thanks for open sourcing the amazing project! I have one question about the evaluation part: How do you select the key frames of ETH3D (or other datasets)? Is it done by setting `num_samples = 8`? Thanks!

**Comment by pschroeppel** [comment]
Hi,
sorry for the late reply!

The keyframe of each sample is indicated via the `keyview_idx` item in the sample dictionary. In the evaluation, it is not really possible to change this, as then also the GT depth, that is stored in the sample dictionary, would not fit anymore to the keyframe. 

Does this answer your question?
best,
Philipp

**Comment by yuqunw** [comment]
Thanks! Yes that does answer my question! Thanks for the information.

**Comment by yuqunw** [comment]
Thanks! Yes that does answer my question! Thanks for the information.
